name: Build and Publish My Custom OpenEMR Image (with Debug)

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: lucirlei/openemr-custom
  OPENEMR_VERSION: '7.0.2'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout DevOps Repository
        uses: actions/checkout@v4

      - name: Checkout OpenEMR Source from My Fork
        uses: actions/checkout@v4
        with:
          repository: lucirlei/openemr
          path: src-openemr

      - name: Log in to Docker Hub
        uses: actions/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ env.OPENEMR_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ================================================================= #
      # ===== PASSO DE DEBUG ADICIONADO AQUI ===== #
      - name: DEBUG - List files in workspace
        run: |
          echo "================================================="
          echo "Conteúdo do diretório de trabalho atual:"
          ls -laR
          echo "================================================="
      # ================================================================= #

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/openemr/${{ env.OPENEMR_VERSION }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
