name: Production 7.0.3 Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    # Only run from master branch on the main repository
    if: github.repository_owner == 'openemr' && github.repository == 'lucirlei/openemr-devops' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get build date
        id: build_date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Build and push 7.0.3 docker
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker/openemr/7.0.3"
          tags: openemr/openemr:7.0.3, openemr/openemr:7.0.3.4, openemr/openemr:7.0.3.4-${{ steps.build_date.outputs.date }}, openemr/openemr:latest
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
